### ISSUE TITLE
plotear el DEM 

### ISSUE THREAD

**Issue by edwin89holiday** [uasd-geografia/racaton#2]
Talibán, me tome el atrevimiento de avanzar en la carga del DEM, claro esta lo hice por otra via creando un directorio, todo bien al carga el raster, pero a la hora de plotearlo me sale elsiguiente error:

plot(mde) 
Error in .doCellFromRowCol(rows, cols, row, col) :    object '_raster_doCellFromRowCol' not found
--

**Comment by geofis** [comment]
Interesante. Pon en un comentario el script para intentar reproducir el error. Por otra parte, prueba reinstalado el paquete raster.

```{r}
install.packages('raster')
```

**Comment by geofis** [comment]
Edwin, si resolviste el problema, es importante que escribas aquí cómo lo resolviste, para así cerrar el issue.

**Comment by edwin89holiday** [comment]
si, solo hay que actualizar el paquete raster hasta que funcione, lo actualice como 3 veces, como dice el refrán " a la tercera es la vencida"

**Comment by geofis** [comment]
Más bien supongo que se debió a que instalé el paquete `raster` como administrador, lo que hizo que estuviera disponible para todos los usuarios.
