### ISSUE TITLE
NO ESTOY CORRIENDO !!!!!

### ISSUE THREAD

**Issue by Maria363** [uasd-geografia/racaton#8]
No me he puesto jabón en los pies, lo que pasa es que yo te explique que no me da acceso a subir los documentos, te mande una captura de pantalla con el problema y me he quedado esperando a tu resuelvas.

**Comment by geofis** [comment]
Aunque no puedas subir documentos, sí que puedes editar/crear código, como por ejemplo, para el pull request [resample-denoise-demcuencas](https://github.com/uasd-geografia/racaton/pull/7). Adelante, lee las instrucciones y dale pa'llá
